// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulationEngine.Infrastructure.DataModel;

namespace SimulationEngine.Infrastructure.Migrations
{
    [DbContext(typeof(SimulationEngineDbContext))]
    partial class SimulationEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("SimulationEngine.Domain.Models.Input", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCircuitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubCircuitId");

                    b.ToTable("inputs");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.LogicGate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortAId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortBId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortCId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortDId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortQId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCircuitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TruthTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortAId")
                        .IsUnique();

                    b.HasIndex("PortBId")
                        .IsUnique();

                    b.HasIndex("PortCId")
                        .IsUnique();

                    b.HasIndex("PortDId")
                        .IsUnique();

                    b.HasIndex("PortQId")
                        .IsUnique();

                    b.HasIndex("SubCircuitId");

                    b.HasIndex("TruthTableId");

                    b.ToTable("logicgates");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Output", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCircuitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubCircuitId");

                    b.ToTable("outputs");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.HasIndex("OutputId");

                    b.ToTable("ports");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.SubCircuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("subcircuits");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.TruthTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Definition")
                        .IsRequired()
                        .HasColumnType("varbinary(81)");

                    b.Property<string>("HeptaIndex")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(27);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("truthtables");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Wire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndPortId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPortId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubCircuitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndPortId")
                        .IsUnique();

                    b.HasIndex("StartPortId");

                    b.HasIndex("SubCircuitId");

                    b.ToTable("wires");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Input", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.SubCircuit", "SubCircuit")
                        .WithMany("Inputs")
                        .HasForeignKey("SubCircuitId");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.LogicGate", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.Port", "PortA")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.LogicGate", "PortAId");

                    b.HasOne("SimulationEngine.Domain.Models.Port", "PortB")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.LogicGate", "PortBId");

                    b.HasOne("SimulationEngine.Domain.Models.Port", "PortC")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.LogicGate", "PortCId");

                    b.HasOne("SimulationEngine.Domain.Models.Port", "PortD")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.LogicGate", "PortDId");

                    b.HasOne("SimulationEngine.Domain.Models.Port", "PortQ")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.LogicGate", "PortQId");

                    b.HasOne("SimulationEngine.Domain.Models.SubCircuit", "SubCircuit")
                        .WithMany("LogicGates")
                        .HasForeignKey("SubCircuitId");

                    b.HasOne("SimulationEngine.Domain.Models.TruthTable", "TruthTable")
                        .WithMany("LogicGates")
                        .HasForeignKey("TruthTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Output", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.SubCircuit", "SubCircuit")
                        .WithMany("Outputs")
                        .HasForeignKey("SubCircuitId");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Port", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.Input", "Input")
                        .WithMany("Ports")
                        .HasForeignKey("InputId");

                    b.HasOne("SimulationEngine.Domain.Models.Output", "Output")
                        .WithMany("Ports")
                        .HasForeignKey("OutputId");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.SubCircuit", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.SubCircuit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("SimulationEngine.Domain.Models.Wire", b =>
                {
                    b.HasOne("SimulationEngine.Domain.Models.Port", "EndPort")
                        .WithOne()
                        .HasForeignKey("SimulationEngine.Domain.Models.Wire", "EndPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimulationEngine.Domain.Models.Port", "StartPort")
                        .WithMany()
                        .HasForeignKey("StartPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimulationEngine.Domain.Models.SubCircuit", "SubCircuit")
                        .WithMany("Wires")
                        .HasForeignKey("SubCircuitId");
                });
#pragma warning restore 612, 618
        }
    }
}
